{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Проверяем что сервис работает"
   ]
  },
  {
   "cell_type": "code",
   "outputs": [],
   "source": [
    "server_url = \"https://applied-python-hw-project.onrender.com\"\n",
    "# server_url = \"http://localhost:5555\""
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:03.882712Z",
     "start_time": "2024-03-20T14:51:03.877852Z"
    }
   },
   "execution_count": 1
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:04.493911Z",
     "start_time": "2024-03-20T14:51:03.882392Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": "b'{\"message\":\"pong\"}'"
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "data = requests.get(server_url + '/ping')\n",
    "data.content"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Обучаем на дефолтных данных"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:04.944620Z",
     "start_time": "2024-03-20T14:51:04.493241Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": "b'{\"message\":\"Model trained on default data and saved successfully\"}'"
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = requests.get(server_url + '/train')\n",
    "data.content"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Обучаем на своих данных"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:06.038797Z",
     "start_time": "2024-03-20T14:51:04.942766Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": "b'{\"message\":\"Model trained on user data  and saved successfully\"}'"
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.datasets import load_iris\n",
    "iris = load_iris()\n",
    "X, y = iris.data, iris.target\n",
    "\n",
    "data = requests.post(server_url + '/train_user',\n",
    "        json= {\n",
    "            'data': X.tolist(),\n",
    "            'target': y.tolist()\n",
    "})\n",
    "data.content"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Предикт 1 объекта и проверяем работу кэша"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:06.920212Z",
     "start_time": "2024-03-20T14:51:06.039554Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": "b'{\"prediction\":[0],\"cashed\":false}'"
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = requests.post(server_url + '/predict',\n",
    "        json= {\n",
    "            'data': X.tolist()[0],\n",
    "})\n",
    "data.content # кэша нет"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:07.783536Z",
     "start_time": "2024-03-20T14:51:06.917059Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": "b'{\"prediction\":[0],\"cashed\":true}'"
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = requests.post(server_url + '/predict',\n",
    "        json= {\n",
    "            'data': X.tolist()[0],\n",
    "})\n",
    "data.content  # кэш есть"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Предикт нескольких объектов и проверяем работу кэша"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:08.271980Z",
     "start_time": "2024-03-20T14:51:07.782116Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": "b'{\"predictions\":[[0],[0]],\"cashed\":[true,false]}'"
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = requests.post(server_url + '/predict/multiple',\n",
    "        json= {\n",
    "            'data': X.tolist()[:2],\n",
    "})\n",
    "data.content"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Предикт 1 объекта в методе предназнченом для нескольких объектов"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:08.676777Z",
     "start_time": "2024-03-20T14:51:08.270818Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": "b'{\"detail\":\"Wrong data format\"}'"
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = requests.post(server_url + '/predict/multiple',\n",
    "        json= {\n",
    "            'data': X.tolist()[0],\n",
    "})\n",
    "data.content # получаем Wrong data format"
   ]
  },
  {
   "cell_type": "code",
   "outputs": [
    {
     "ename": "ResponseError",
     "evalue": "Client IP address is not in the allowlist.",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mResponseError\u001B[0m                             Traceback (most recent call last)",
      "Cell \u001B[0;32mIn[9], line 8\u001B[0m\n\u001B[1;32m      6\u001B[0m \u001B[38;5;66;03m# Проверяем соединение, отправляя команду PING\u001B[39;00m\n\u001B[1;32m      7\u001B[0m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[0;32m----> 8\u001B[0m     response \u001B[38;5;241m=\u001B[39m \u001B[43mredis_client\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mping\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m      9\u001B[0m     \u001B[38;5;28;01mif\u001B[39;00m response:\n\u001B[1;32m     10\u001B[0m         \u001B[38;5;28mprint\u001B[39m(\u001B[38;5;124m\"\u001B[39m\u001B[38;5;124mСоединение с Redis успешно установлено через SSL.\u001B[39m\u001B[38;5;124m\"\u001B[39m)\n",
      "File \u001B[0;32m~/Documents/Магистратура/Прикладной питон/applied_python_hw_project/.venv/lib/python3.10/site-packages/redis/commands/core.py:1217\u001B[0m, in \u001B[0;36mManagementCommands.ping\u001B[0;34m(self, **kwargs)\u001B[0m\n\u001B[1;32m   1211\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21mping\u001B[39m(\u001B[38;5;28mself\u001B[39m, \u001B[38;5;241m*\u001B[39m\u001B[38;5;241m*\u001B[39mkwargs) \u001B[38;5;241m-\u001B[39m\u001B[38;5;241m>\u001B[39m ResponseT:\n\u001B[1;32m   1212\u001B[0m \u001B[38;5;250m    \u001B[39m\u001B[38;5;124;03m\"\"\"\u001B[39;00m\n\u001B[1;32m   1213\u001B[0m \u001B[38;5;124;03m    Ping the Redis server\u001B[39;00m\n\u001B[1;32m   1214\u001B[0m \n\u001B[1;32m   1215\u001B[0m \u001B[38;5;124;03m    For more information see https://redis.io/commands/ping\u001B[39;00m\n\u001B[1;32m   1216\u001B[0m \u001B[38;5;124;03m    \"\"\"\u001B[39;00m\n\u001B[0;32m-> 1217\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mexecute_command\u001B[49m\u001B[43m(\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mPING\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m*\u001B[39;49m\u001B[38;5;241;43m*\u001B[39;49m\u001B[43mkwargs\u001B[49m\u001B[43m)\u001B[49m\n",
      "File \u001B[0;32m~/Documents/Магистратура/Прикладной питон/applied_python_hw_project/.venv/lib/python3.10/site-packages/redis/client.py:540\u001B[0m, in \u001B[0;36mRedis.execute_command\u001B[0;34m(self, *args, **options)\u001B[0m\n\u001B[1;32m    538\u001B[0m pool \u001B[38;5;241m=\u001B[39m \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39mconnection_pool\n\u001B[1;32m    539\u001B[0m command_name \u001B[38;5;241m=\u001B[39m args[\u001B[38;5;241m0\u001B[39m]\n\u001B[0;32m--> 540\u001B[0m conn \u001B[38;5;241m=\u001B[39m \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39mconnection \u001B[38;5;129;01mor\u001B[39;00m \u001B[43mpool\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mget_connection\u001B[49m\u001B[43m(\u001B[49m\u001B[43mcommand_name\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m*\u001B[39;49m\u001B[38;5;241;43m*\u001B[39;49m\u001B[43moptions\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    542\u001B[0m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[1;32m    543\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m conn\u001B[38;5;241m.\u001B[39mretry\u001B[38;5;241m.\u001B[39mcall_with_retry(\n\u001B[1;32m    544\u001B[0m         \u001B[38;5;28;01mlambda\u001B[39;00m: \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39m_send_command_parse_response(\n\u001B[1;32m    545\u001B[0m             conn, command_name, \u001B[38;5;241m*\u001B[39margs, \u001B[38;5;241m*\u001B[39m\u001B[38;5;241m*\u001B[39moptions\n\u001B[1;32m    546\u001B[0m         ),\n\u001B[1;32m    547\u001B[0m         \u001B[38;5;28;01mlambda\u001B[39;00m error: \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39m_disconnect_raise(conn, error),\n\u001B[1;32m    548\u001B[0m     )\n",
      "File \u001B[0;32m~/Documents/Магистратура/Прикладной питон/applied_python_hw_project/.venv/lib/python3.10/site-packages/redis/connection.py:1104\u001B[0m, in \u001B[0;36mConnectionPool.get_connection\u001B[0;34m(self, command_name, *keys, **options)\u001B[0m\n\u001B[1;32m   1100\u001B[0m     \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39m_in_use_connections\u001B[38;5;241m.\u001B[39madd(connection)\n\u001B[1;32m   1102\u001B[0m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[1;32m   1103\u001B[0m     \u001B[38;5;66;03m# ensure this connection is connected to Redis\u001B[39;00m\n\u001B[0;32m-> 1104\u001B[0m     \u001B[43mconnection\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mconnect\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m   1105\u001B[0m     \u001B[38;5;66;03m# connections that the pool provides should be ready to send\u001B[39;00m\n\u001B[1;32m   1106\u001B[0m     \u001B[38;5;66;03m# a command. if not, the connection was either returned to the\u001B[39;00m\n\u001B[1;32m   1107\u001B[0m     \u001B[38;5;66;03m# pool before all data has been read or the socket has been\u001B[39;00m\n\u001B[1;32m   1108\u001B[0m     \u001B[38;5;66;03m# closed. either way, reconnect and verify everything is good.\u001B[39;00m\n\u001B[1;32m   1109\u001B[0m     \u001B[38;5;28;01mtry\u001B[39;00m:\n",
      "File \u001B[0;32m~/Documents/Магистратура/Прикладной питон/applied_python_hw_project/.venv/lib/python3.10/site-packages/redis/connection.py:288\u001B[0m, in \u001B[0;36mAbstractConnection.connect\u001B[0;34m(self)\u001B[0m\n\u001B[1;32m    285\u001B[0m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[1;32m    286\u001B[0m     \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39mredis_connect_func \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m:\n\u001B[1;32m    287\u001B[0m         \u001B[38;5;66;03m# Use the default on_connect function\u001B[39;00m\n\u001B[0;32m--> 288\u001B[0m         \u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mon_connect\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    289\u001B[0m     \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[1;32m    290\u001B[0m         \u001B[38;5;66;03m# Use the passed function redis_connect_func\u001B[39;00m\n\u001B[1;32m    291\u001B[0m         \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39mredis_connect_func(\u001B[38;5;28mself\u001B[39m)\n",
      "File \u001B[0;32m~/Documents/Магистратура/Прикладной питон/applied_python_hw_project/.venv/lib/python3.10/site-packages/redis/connection.py:354\u001B[0m, in \u001B[0;36mAbstractConnection.on_connect\u001B[0;34m(self)\u001B[0m\n\u001B[1;32m    351\u001B[0m \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39msend_command(\u001B[38;5;124m\"\u001B[39m\u001B[38;5;124mAUTH\u001B[39m\u001B[38;5;124m\"\u001B[39m, \u001B[38;5;241m*\u001B[39mauth_args, check_health\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mFalse\u001B[39;00m)\n\u001B[1;32m    353\u001B[0m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[0;32m--> 354\u001B[0m     auth_response \u001B[38;5;241m=\u001B[39m \u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mread_response\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    355\u001B[0m \u001B[38;5;28;01mexcept\u001B[39;00m AuthenticationWrongNumberOfArgsError:\n\u001B[1;32m    356\u001B[0m     \u001B[38;5;66;03m# a username and password were specified but the Redis\u001B[39;00m\n\u001B[1;32m    357\u001B[0m     \u001B[38;5;66;03m# server seems to be < 6.0.0 which expects a single password\u001B[39;00m\n\u001B[1;32m    358\u001B[0m     \u001B[38;5;66;03m# arg. retry auth with just the password.\u001B[39;00m\n\u001B[1;32m    359\u001B[0m     \u001B[38;5;66;03m# https://github.com/andymccurdy/redis-py/issues/1274\u001B[39;00m\n\u001B[1;32m    360\u001B[0m     \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39msend_command(\u001B[38;5;124m\"\u001B[39m\u001B[38;5;124mAUTH\u001B[39m\u001B[38;5;124m\"\u001B[39m, auth_args[\u001B[38;5;241m-\u001B[39m\u001B[38;5;241m1\u001B[39m], check_health\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mFalse\u001B[39;00m)\n",
      "File \u001B[0;32m~/Documents/Магистратура/Прикладной питон/applied_python_hw_project/.venv/lib/python3.10/site-packages/redis/connection.py:536\u001B[0m, in \u001B[0;36mAbstractConnection.read_response\u001B[0;34m(self, disable_decoding, disconnect_on_error, push_request)\u001B[0m\n\u001B[1;32m    534\u001B[0m \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28misinstance\u001B[39m(response, ResponseError):\n\u001B[1;32m    535\u001B[0m     \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[0;32m--> 536\u001B[0m         \u001B[38;5;28;01mraise\u001B[39;00m response\n\u001B[1;32m    537\u001B[0m     \u001B[38;5;28;01mfinally\u001B[39;00m:\n\u001B[1;32m    538\u001B[0m         \u001B[38;5;28;01mdel\u001B[39;00m response  \u001B[38;5;66;03m# avoid creating ref cycles\u001B[39;00m\n",
      "\u001B[0;31mResponseError\u001B[0m: Client IP address is not in the allowlist."
     ]
    }
   ],
   "source": [
    "import redis\n",
    "\n",
    "redis_url = 'rediss://red-cnte8nvsc6pc73cb03gg:peBJvfhrCZPT24NIqTUThCwEKBbIIoQP@frankfurt-redis.render.com:6379'\n",
    "redis_client = redis.Redis.from_url(redis_url, ssl_cert_reqs=None)\n",
    "\n",
    "# Проверяем соединение, отправляя команду PING\n",
    "try:\n",
    "    response = redis_client.ping()\n",
    "    if response:\n",
    "        print(\"Соединение с Redis успешно установлено через SSL.\")\n",
    "    else:\n",
    "        print(\"Получен неожиданный ответ от Redis.\")\n",
    "except (redis.ConnectionError, redis.TimeoutError) as e:\n",
    "    print(f\"Ошибка подключения к Redis: {e}\")"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-03-20T14:51:10.423685Z",
     "start_time": "2024-03-20T14:51:08.676988Z"
    }
   },
   "execution_count": 9
  },
  {
   "cell_type": "code",
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "start_time": "2024-03-20T14:51:10.423101Z"
    }
   },
   "execution_count": null
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "adv_py",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
